version: "3.2"

services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    #env_file:
    #  - .env
    volumes:
      - postgres-volume:/var/lib/postgresql
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql

  client:
    container_name: client
    build: ./client
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:3000
    ports:
      - "3000:3000"
    command:
      [
        "dotnet",
        "watch",
        "run",
        -v,
        "--non-interactive",
        "--project",
        "client/client.csproj",
        "--urls",
        "http://0.0.0.0:3000"
      ]
    volumes:
      - ./client/:/app
      - /app/obj/ # <- directory won't be mounted
      - /app/bin/ # <- directory won't be mounted
      - /app/client/obj/ # <- directory won't be mounted
      - /app/client/bin/ # <- directory won't be mounted
      - ~/.aspnet/https:/https:ro

  server:
    container_name: server
    build: ./server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=123
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "5001:80"
      - "5002:443"
    command:
      [
        "dotnet",
        "watch",
        "run",
        -v,
        "--non-interactive",
        "--project",
        "server/server.csproj",
      ]
    volumes:
      - ./server/:/app
      - /app/obj/ # <- directory won't be mounted
      - /app/bin/ # <- directory won't be mounted
      - /app/server/obj/ # <- directory won't be mounted
      - /app/server/bin/ # <- directory won't be mounted
      - ~/.aspnet/https:/https:ro

volumes:
  postgres-volume:
    external: true
